[package]
name = "loopmaster-audio-windows"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
loopmaster-audio-core = { path = "../audio-core" }
thiserror.workspace = true
windows = { version = "0.61", features = [
    "Win32_Foundation",
    "Win32_Media_Audio",
    "Win32_System_Com",
    "Win32_System_Com_StructuredStorage",
    "Win32_System_Variant",
    "Win32_System_Threading",
    "Win32_System_Ole",
    "Win32_Security",
    "Win32_Storage_FileSystem",
    "Win32_Devices_FunctionDiscovery",
    "Win32_UI_Shell_PropertiesSystem",
    "Win32_UI_Shell",
    "Win32_UI_WindowsAndMessaging",
    "Win32_Graphics_Gdi",
    "Win32_Graphics_GdiPlus",
] }
windows-core = "0.61.2"
