[package]
name = "loopmaster-app"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
build = "build.rs"

[dependencies]
loopmaster-audio-core = { path = "../audio-core" }
loopmaster-audio-windows = { path = "../audio-windows" }
loopmaster-app-service = { path = "../app-service" }
slint = "1.13"

[build-dependencies]
slint-build = "1.13"

